// Mocks generated by Mockito 5.2.0 from annotations
// in bytebank/test/widgets/dashboard_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:bytebank/dao/contact_dao.dart' as _i2;
import 'package:bytebank/models/contact.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ContactDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactDao extends _i1.Mock implements _i2.ContactDao {
  MockContactDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> save(_i4.Contact? contato) =>
      (super.noSuchMethod(Invocation.method(#save, [contato]),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<List<_i4.Contact>> listAll() =>
      (super.noSuchMethod(Invocation.method(#listAll, []),
              returnValue: Future<List<_i4.Contact>>.value(<_i4.Contact>[]))
          as _i3.Future<List<_i4.Contact>>);
  @override
  List<_i4.Contact> toList(List<Map<String, dynamic>>? results) =>
      (super.noSuchMethod(Invocation.method(#toList, [results]),
          returnValue: <_i4.Contact>[]) as List<_i4.Contact>);
}
